name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  clone_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean and Clone git
        run: |
          rm -rf *
          git clone https://github.com/Haknin/crypto-site.git

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Cleanup Container
        run: |
          pip install docker
          echo "apply the script"
          cd crypto-site/
          python3 pythonversioning.py
          

      - name: Build And Push The Image To Docker Hub
        working-directory: crypto-site
        run: |
          docker build -t haknin/crypto_docker:1.${{ github.run_number }} -t haknin/crypto_docker:latest .
          docker push haknin/crypto_docker:1.${{ github.run_number }}
          docker push haknin/crypto_docker:latest
          docker image ls --format '{{.ID}}' haknin/crypto_docker --filter 'dangling=false' | sort -r | awk 'NR>4' | xargs -I {} docker image rm -f {}

          
  deploy:
    runs-on: ubuntu-latest
    needs: clone_and_build
    steps:
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            project_id: ${{ secrets.gcp_project }}
            service_account_key: ${{ secrets.gcp_credentials }}
            export_default_credentials: true
            run: |
              gcloud components install gke-gcloud-auth-plugin

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: '345.0.0'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Download Helm Chart
        run: |
          gsutil cp gs://bucket-haknin/helm-project-0.1.9.tgz helm.tgz
          tar -xzvf helm.tgz

      - name: Configure Google Kubernetes Engine (GKE) credentials
        run: |
          gcloud container clusters get-credentials cluster-1093 --region=us-central1-c

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install myapp flaskapp/ --set image.tag=1.${{ github.run_number }}
      - name: Find your inner IP
        run: |
          chmod +x crypto-site/Load-Balancer-IP.sh
          bash crypto-site/Load-Balancer-IP.sh
